export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';

//**********************//
//ASYNC OPERATIONS TYPES//
//**********************//

// Get deals from firebase
export const GET_TOPDEALS = 'GET_TOPDEALS';
export const GET_TOPDEALS_START = 'GET_TOPDEALS_START';
export const GET_TOPDEALS_SUCCEED = 'GET_TOPDEALS_SUCCEED';
export const GET_TOPDEALS_FAIL = 'GET_TOPDEALS_FAIL';

// Get information about the venue
export const GET_VENUEINFORMATION = 'GET_VENUEINFORMATION';
export const GET_VENUEINFORMATION_START = 'GET_VENUEINFORMATION_START';
export const GET_VENUEINFORMATION_SUCCEED = 'GET_VENUEINFORMATION_SUCCEED';
export const GET_VENUEINFORMATION_FAIL = 'GET_VENUEINFORMATION_FAIL';