require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'drinksApp' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'drinksAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({'Flipper' => '0.78.0'})
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
  
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

target 'drinksApp-tvOS' do
  # Pods for drinksApp-tvOS

  target 'drinksApp-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
